# Generated by Django 4.2.7 on 2023-11-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='course_lesson_file/'),
        ),
    ]
