# Generated by Django 4.2.7 on 2023-11-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_courselesson_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='courser_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
