# Generated by Django 4.2.7 on 2023-11-07 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_buycourse_course_id_alter_buycourse_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='courser_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course.course'),
        ),
    ]
