# Generated by Django 4.2.7 on 2023-11-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtobe', '0002_rename_data_channeluser_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels_category', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='channeluser',
            name='channel_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youtobe.channelscategory'),
        ),
    ]
