# Generated by Django 4.2.7 on 2023-11-14 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_caretopichistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimages',
            name='plant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='plants.plants'),
        ),
    ]
