# Generated by Django 4.2.7 on 2023-11-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_caretopichistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPlantMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
