# Generated by Django 4.2.7 on 2023-11-14 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0003_locationplantmarket'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretopics',
            name='care_topic_view_user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationplantmarket',
            name='location_img',
            field=models.ImageField(blank=True, null=True, upload_to='shops/'),
        ),
    ]
