# Generated by Django 4.2.7 on 2023-11-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_plantimages_plant_id'),
        ('plants', '0004_caretopics_care_topic_view_user_and_more'),
    ]

    operations = [
    ]
