# Generated by Django 4.2.7 on 2023-11-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_careplanting_care_plant_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplanting',
            name='care_plant_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
